# Container-based builds used if "sudo: false" --> fast boot (1-6s)
# https://docs.travis-ci.com/user/ci-environment/
sudo: false
dist: trusty

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

env:
    matrix:
        - DJANGO="1.8"
        - DJANGO="1.9"
        - DJANGO="1.10"
        - DJANGO="1.11"

matrix:
    include:
        # The Django 1.8 series is the last to support Python 3.2 and 3.3.
        - python: "3.3"
          env: DJANGO="1.8"
        # Django 1.11 is the first release to support Python 3.6.
        - python: "3.6"
          env: DJANGO="1.11"

install:
    - pip install tox

script:
    - tox -vvvv -e $( echo $TRAVIS_PYTHON_VERSION | sed -e 's/^2\./py2/' -e 's/^3\./py3/' )-django${DJANGO}
